from rest_framework import routers
from web import api_views as views

router = routers.DefaultRouter()
router.register(r'bicycle', views.BicycleViewset)
router.register(r'bicycletubeusage', views.BicycletubeusageViewset)
router.register(r'bikeparts', views.BikepartsViewset)
router.register(r'biketubes', views.BiketubesViewset)
router.register(r'city', views.CityViewset)
router.register(r'component', views.ComponentViewset)
router.register(r'customer', views.CustomerViewset)
router.register(r'employee', views.EmployeeViewset)
router.register(r'customertransaction', views.CustomertransactionViewset)
router.register(r'groupcomponent', views.GroupcomponentsViewset)
router.register(r'groupo', views.GroupoViewset)
router.register(r'manufacturer', views.ManufacturerViewset)
router.register(r'manufacturertransaction', views.ManufacturertransactionViewset)
router.register(r'paint', views.PaintViewset)
router.register(r'purchaseitem', views.PurchaseitemViewset)
router.register(r'purchaseorder', views.PurchaseorderViewset)
router.register(r'retailstore', views.RetailstoreViewset)
router.register(r'revisionhistory', views.RevisionhistoryViewset)
router.register(r'samplename', views.SamplenameViewset)
router.register(r'samplestreet', views.SamplestreetViewset)
router.register(r'tubematerial', views.TubematerialViewset)