name: Django CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install djangorestframework
        pip install django-filter
        pip install django-crispy-forms
        pip install mysqlclient
        pip install requests
    - name: Copy Config
      run: |
        cp api/configs/config.py.example api/configs/config.py
    - name: Run Tests
      run: |
        python api/manage.py test --keepdb
